# Generated by Django 5.2.7 on 2025-10-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_headline', models.CharField(default='歡迎來到我的網站！', max_length=120, verbose_name='首頁歡迎頭條')),
                ('about_text', models.TextField(default='這裡放你的簡介、背景與興趣。', verbose_name='關於－簡短簡介')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯繫 Email')),
                ('social_x', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('social_ig', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_fb', models.URLField(blank=True, verbose_name='Facebook')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '網站內容設定',
                'verbose_name_plural': '網站內容設定',
            },
        ),
    ]
